<?php
$OWNER_NAME=$_POST['OWNER_NAME'];
$OWNER_ADDRESS=$_POST['OWNER_ADDRESS'];
$VEHICLE_REGISTERATION_NUMBER=$_POST['VEHICLE_REGISTERATION_NUMBER'];
$INSURANCE_COMPANY=$_POST['INSURANCE_COMPANY'];
$INSURANCE_NUMBER=$_POST['INSURANCE_NUMBER'];
$LICENSE_NUMBER=$_POST['LICENSE_NUMBER'];
$VEHICLE_NAME=$_POST['VEHICLE_NAME'];
$VEHICLE_MODLE=$_POST['VEHICLE_MODLE'];
$VEHICLE_COLOUR=$_POST['VEHICLE_COLOUR'];
$REGISTERED_DATE=$_POST['REGISTERED_DATE'];
$INSURENCE_STARTING_DATE=$_POST['INSURENCE_STARTING_DATE'];
$INSURENCE_EXPIRY_DATE=$_POST['INSURENCE_EXPIRY_DATE'];
$a=mysqli_connect("localhost","root","","insurance");
if(!$a)
{
echo "error";
}
else
{
$sql="INSERT INTO vehicle VALUES('".$OWNER_NAME."','".$OWNER_ADDRESS."','".$VEHICLE_REGISTERATION_NUMBER."','".$INSURANCE_COMPANY."','".$INSURANCE_NUMBER."','".$LICENSE_NUMBER."','".$VEHICLE_NAME."','".$VEHICLE_MODLE."','".$VEHICLE_COLOUR."','".$REGISTERED_DATE."','".$INSURENCE_STARTING_DATE."','".$INSURENCE_EXPIRY_DATE."')";

if (!mysqli_query($a,$sql))
{
die ("error".mysqli_error($a));
}
else
{
header('location:home.html');
}
}
?>
